version: '2'
services:
    rutorrent-develop:
      image: romancin/rutorrent-flood:develop
      container_name: rutorrent-flood-develop
      networks:
        - default
      tty: true
      volumes:
        - /share/Container/rutorrent-flood-develop:/config
        - /share/Container/rutorrent-flood-develop/downloads:/downloads
      environment:
        - PUID=0
        - PGID=0
        - TZ=Europe/Madrid
        - CREATE_SUBDIR_BY_TRACKERS=NO
      ports:
        - "7443:443"
        - "32316:52316"
        - "3002:3000"
networks:
  default:
    external:
      name: main_network
